plugins {
    id 'com.android.application'
}

android {
    namespace 'com.radman.boost'
    compileSdk 35

    defaultConfig {
        applicationId 'com.radman.boost'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
